<a href="https://colab.research.google.com/github/HyojinKim88/linear_algebra/blob/master/3%2C4_%ED%96%89%EB%A0%AC_%EB%84%98%ED%8C%8C%EC%9D%B4_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [3]:
A= np.array([[2,7],[3,4],[6,1]])
B =np.array([[1,4],[4,-1],[2,5]])

# 3. 행렬

In [5]:
print(A+B)

[[ 3 11]
 [ 7  3]
 [ 8  6]]


In [6]:
A+B

array([[ 3, 11],
       [ 7,  3],
       [ 8,  6]])

In [8]:
# 행렬의 원소곱 -> 두 행렬의 크기가 동일
np.multiply(A,B)

array([[ 2, 28],
       [12, -4],
       [12,  5]])

In [10]:
# 행렬 곱 -> 한 행렬의 행길이, 다른 행렬의 열길이 같음
np.matmul(A,B.T)

array([[30,  1, 39],
       [19,  8, 26],
       [10, 23, 17]])

# 4. 다양한 행렬

## 대칭 행렬
- 대칭 행렬 간 덧셈, 뺄셈 -> 대칭 행렬
- 대칭 행렬곱 -> 반드시 대칭은 아님
- 대칭 행렬의 거듭 제곱 -> 대칭행렬

- $AA^T$, $A^TA$ -> 대칭행렬 (A는 대칭행렬이 아니어도 됨)

In [11]:
# A는 대칭행렬
A = np.array([[1,0,2],
              [0,2,1],
              [2,1,1]])

In [13]:
At = A.T
print(At)

[[1 0 2]
 [0 2 1]
 [2 1 1]]


In [14]:
A == At

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [15]:
# 거듭 제곱 행렬
AA = A
for i in range(0,9):
  AA = np.matmul(AA, A)
  print(f"행렬 A의 {i+2} 제곱은")
  print(AA)
  print("---------------")

행렬 A의 2 제곱은
[[5 2 4]
 [2 5 3]
 [4 3 6]]
---------------
행렬 A의 3 제곱은
[[13  8 16]
 [ 8 13 12]
 [16 12 17]]
---------------
행렬 A의 4 제곱은
[[45 32 50]
 [32 38 41]
 [50 41 61]]
---------------
행렬 A의 5 제곱은
[[145 114 172]
 [114 117 143]
 [172 143 202]]
---------------
행렬 A의 6 제곱은
[[489 400 576]
 [400 377 488]
 [576 488 689]]
---------------
행렬 A의 7 제곱은
[[1641 1376 1954]
 [1376 1242 1665]
 [1954 1665 2329]]
---------------
행렬 A의 8 제곱은
[[5549 4706 6612]
 [4706 4149 5659]
 [6612 5659 7902]]
---------------
행렬 A의 9 제곱은
[[18773 16024 22416]
 [16024 13957 19220]
 [22416 19220 26785]]
---------------
행렬 A의 10 제곱은
[[63605 54464 75986]
 [54464 47134 65225]
 [75986 65225 90837]]
---------------


In [19]:
np.matmul(A, At)

array([[5, 2, 4],
       [2, 5, 3],
       [4, 3, 6]])

In [20]:
np.matmul(At, A)

array([[5, 2, 4],
       [2, 5, 3],
       [4, 3, 6]])

## 대각 행렬 D
- 주대각 원소가 0이 아닌 행렬 (반드시 정방 행렬이 아니어도 됨)
- $D^{-1}$ : 주 대각 원소의 역수
- $D^n$ : 대각 원소에 n제곱

### 대각 행렬의 성질
- 기준 행렬의 오른쪽에 행렬곱 $AD$ -> 열 원소가 대각행렬의 배수
- 기준 행렬의 왼쪽에 행렬곱 $DA$ -> 행 원소가 대각행렬의 배수

In [21]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
D = np.diag(A)
print(D)

[1 5 9]


In [22]:
print(np.diag(D))

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [23]:
D = np.diag([1,2,3])
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [25]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
AD = np.matmul(A,D)
print(AD)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [27]:
DA = np.matmul(D,A)
print(DA)

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


## 단위 행렬 I
- 주 대각 원소가 1이고 나머지는 모두 0인 행렬
- 성질
  - $AI = IA = A$

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 영행렬

In [31]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## 삼각행렬
- 상삼각행렬, 하삼각행렬
- 성질
  - 삼각 행렬 간 덧셈, 뺄셈, 행렬곱의 결과는 삼각행렬
  - 상 삼각 행렬의 전치 행렬 : 하삼각행렬
  - 삼각 행렬의 역행렬도 삼각 행렬

In [5]:
 A = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [6]:
np.triu(A)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [7]:
np.tril(A)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

## 토플리츠 행렬
- 시계열 분석에 자주 사용됨 : 시점에 따라 값이 나열된 형태
- $T_{i,j} = T_{i+1, j+1} = t_{i-j}$

In [8]:
from scipy.linalg import toeplitz #넘파이에서는 제공 X

만드는 법<br>
1행은  [1,3,5,7,9]부터 시작<br>
1행의 원소는 우하향, 한 칸씩 이동<br>
빈 칸부터 [1,0,-2,-4]가 순서대로 채워지며 역시 우하향, 한 칸씩 이동<br>

In [9]:
A = toeplitz([1,0,-2,-4],
             [1,3,5,7,9])
print(A)
# toeplitz() takes from 1 to 2 positional arguments

[[ 1  3  5  7  9]
 [ 0  1  3  5  7]
 [-2  0  1  3  5]
 [-4 -2  0  1  3]]


## 이중 대각 행렬
대각원소의 바로 위 또는 아래 원소가 0이 아닌 행렬
- upper bidiagonal matrix
- lower bidiagonal matrix

In [14]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
diag = np.diag(A)
print(diag)

[1 5 9]


In [15]:
np.diag(diag)

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [16]:
np.diag(diag, k=1) #k=1 : 대각원소 1칸 위에 있는 원소를 추출한다. / k=-1 : 대각원소 1칸 아래의 원소를 추출

array([[0, 1, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 9],
       [0, 0, 0, 0]])

In [19]:
u_diag = np.diag(A, k=1)
print(u_diag)

[2 6]


In [20]:
# upper bidiagonal matrix
np.diag(diag) + np.diag(u_diag, k=1)

array([[1, 2, 0],
       [0, 5, 6],
       [0, 0, 9]])

## 하우스홀더 행렬 H
- 어떤 행렬을 다른 행렬로 변환할 때 사용하는 행렬 중 하나.
- 정사각 행렬, 모든 열이 정규 직교(orthonomal)
- 벡터 $v$, 단위 행렬$I$를 이용해 구함
- $ H = I - 2 * vv^T/v^Tv$




In [21]:
v = np.array([1,0,2,3])

In [22]:
n=len(v)
print(n)

4


In [23]:
# 외적 : v*v^T
outer_mat = np.outer(v,v) 
print(outer_mat)

[[1 0 2 3]
 [0 0 0 0]
 [2 0 4 6]
 [3 0 6 9]]


In [24]:
# 내적 : v^T*v
inner_val = np.inner(v,v)
print(inner_val)

14


In [26]:
I = np.eye(n)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
H = I -(2 / inner_val)*outer_mat
H

array([[ 0.85714286,  0.        , -0.28571429, -0.42857143],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.28571429,  0.        ,  0.42857143, -0.85714286],
       [-0.42857143,  0.        , -0.85714286, -0.28571429]])